version: '3.5'
networks:
  back-tier:
    driver: bridge

services:
  connect-be:
    image: connect-be
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      DATA_FILE: "/tmp/sample.json"
    volumes:
      - "./data:/tmp"
    ports:
      - "8080:8080"
#    networks:
#      - back-tier
    restart: always

  connect-fe:
    image: connect-fe
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "8001:8001"
    restart: always