// @generated by protoc-gen-es v1.10.0
// @generated from file greet.proto (package greet, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message greet.SMSAnalysisRequest
 */
export declare class SMSAnalysisRequest extends Message<SMSAnalysisRequest> {
  /**
   * @generated from field: int64 number = 1;
   */
  number: bigint;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  constructor(data?: PartialMessage<SMSAnalysisRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "greet.SMSAnalysisRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SMSAnalysisRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SMSAnalysisRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SMSAnalysisRequest;

  static equals(a: SMSAnalysisRequest | PlainMessage<SMSAnalysisRequest> | undefined, b: SMSAnalysisRequest | PlainMessage<SMSAnalysisRequest> | undefined): boolean;
}

/**
 * @generated from message greet.PrefixMatch
 */
export declare class PrefixMatch extends Message<PrefixMatch> {
  /**
   * @generated from field: int64 prefix = 1;
   */
  prefix: bigint;

  /**
   * @generated from field: string operator = 2;
   */
  operator: string;

  /**
   * @generated from field: int64 country_code = 3;
   */
  countryCode: bigint;

  /**
   * @generated from field: string country_name = 4;
   */
  countryName: string;

  constructor(data?: PartialMessage<PrefixMatch>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "greet.PrefixMatch";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PrefixMatch;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PrefixMatch;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PrefixMatch;

  static equals(a: PrefixMatch | PlainMessage<PrefixMatch> | undefined, b: PrefixMatch | PlainMessage<PrefixMatch> | undefined): boolean;
}

/**
 * @generated from message greet.SMSAnalysisResponse
 */
export declare class SMSAnalysisResponse extends Message<SMSAnalysisResponse> {
  /**
   * @generated from field: greet.PrefixMatch prefix = 1;
   */
  prefix?: PrefixMatch;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  constructor(data?: PartialMessage<SMSAnalysisResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "greet.SMSAnalysisResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SMSAnalysisResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SMSAnalysisResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SMSAnalysisResponse;

  static equals(a: SMSAnalysisResponse | PlainMessage<SMSAnalysisResponse> | undefined, b: SMSAnalysisResponse | PlainMessage<SMSAnalysisResponse> | undefined): boolean;
}

