// @generated by protoc-gen-es v1.10.0
// @generated from file greet.proto (package greet, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message greet.SMSAnalysisRequest
 */
export const SMSAnalysisRequest = /*@__PURE__*/ proto3.makeMessageType(
  "greet.SMSAnalysisRequest",
  () => [
    { no: 1, name: "number", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message greet.PrefixMatch
 */
export const PrefixMatch = /*@__PURE__*/ proto3.makeMessageType(
  "greet.PrefixMatch",
  () => [
    { no: 1, name: "prefix", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "operator", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "country_code", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "country_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message greet.SMSAnalysisResponse
 */
export const SMSAnalysisResponse = /*@__PURE__*/ proto3.makeMessageType(
  "greet.SMSAnalysisResponse",
  () => [
    { no: 1, name: "prefix", kind: "message", T: PrefixMatch },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

