// @generated by protoc-gen-connect-es v1.4.0
// @generated from file greet.proto (package greet, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { SMSAnalysisRequest, SMSAnalysisResponse } from "./greet_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service greet.GreetService
 */
export declare const GreetService: {
  readonly typeName: "greet.GreetService",
  readonly methods: {
    /**
     * @generated from rpc greet.GreetService.Greet
     */
    readonly greet: {
      readonly name: "Greet",
      readonly I: typeof SMSAnalysisRequest,
      readonly O: typeof SMSAnalysisResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

